---
- hosts: all
  become: yes
  vars:
    - myname: templates examples
  tasks:
  - name: create a file with static content
    copy:
      src: hello.txt
      dest: /home/ansible/hello
  - name: create a file with dynamic content 
    template:
      scr: messages.j2
      dest: /home/ansible/message
    