---
- hosts: dbserver
  become: yes
  tasks:
  - name: install tomcat8 
    apt:
      name: tomcat8
      state: present
      update_cache: yes
  - name: install tomcat packages
    apt: 
      name: "{{ item }}"
      state: present
    loop:
     - tomcat8-docs 
     - tomcat8-examples
     - tomcat8-admin
  - name: restart tomcat
    service:
      name: tomcat8
      state: restarted